const express=require('express');const {canBorrow,ratingDelta}=require('./rules');const app=express();app.use(express.json());
const urls={library:process.env.LIBRARY_URL||'http://library-service:8060',reservation:process.env.RESERVATION_URL||'http://reservation-service:8070',rating:process.env.RATING_URL||'http://rating-service:8050'};
async function call(url,options={}){const r=await fetch(url,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});const data=r.status===204?null:await r.json().catch(()=>null);if(!r.ok){const e=new Error(data?.message||'Upstream request failed');e.status=r.status;e.payload=data;throw e}return data}
const query=(q)=>new URLSearchParams(Object.entries(q).filter(([,v])=>v!==undefined&&v!==''));const user=(req)=>req.get('X-User-Name');
app.get('/manage/health',(_q,r)=>r.sendStatus(200));
app.get('/api/v1/libraries',async(q,r,n)=>{try{if(!q.query.city)return r.status(400).json({message:'city is required'});const p=query({city:q.query.city,page:q.query.page||1,size:q.query.size||10});r.json(await call(`${urls.library}/internal/libraries?${p}`))}catch(e){n(e)}});
app.get('/api/v1/libraries/:uid/books',async(q,r,n)=>{try{const p=query({page:q.query.page||1,size:q.query.size||25,showAll:q.query.showAll||false});r.json(await call(`${urls.library}/internal/libraries/${q.params.uid}/books?${p}`))}catch(e){n(e)}});
app.get('/api/v1/rating',async(q,r,n)=>{try{if(!user(q))return r.status(400).json({message:'X-User-Name is required'});r.json(await call(`${urls.rating}/internal/rating/${encodeURIComponent(user(q))}`))}catch(e){n(e)}});
app.get('/api/v1/reservations',async(q,r,n)=>{try{if(!user(q))return r.status(400).json({message:'X-User-Name is required'});const reservations=await call(`${urls.reservation}/internal/reservations?username=${encodeURIComponent(user(q))}`);const out=await Promise.all(reservations.map(async x=>{const b=await call(`${urls.library}/internal/books/${x.bookUid}/libraries/${x.libraryUid}`);return {reservationUid:x.reservationUid,status:x.status,startDate:x.startDate,tillDate:x.tillDate,book:{bookUid:b.bookUid,name:b.name,author:b.author,genre:b.genre},library:{libraryUid:b.libraryUid,name:b.libraryName,address:b.address,city:b.city}}}));r.json(out)}catch(e){n(e)}});
app.post('/api/v1/reservations',async(q,r,n)=>{try{const username=user(q),{bookUid,libraryUid,tillDate}=q.body||{};if(!username||!bookUid||!libraryUid||!tillDate)return r.status(400).json({message:'X-User-Name, bookUid, libraryUid and tillDate are required'});const active=await call(`${urls.reservation}/internal/reservations?username=${encodeURIComponent(username)}`);const rating=await call(`${urls.rating}/internal/rating/${encodeURIComponent(username)}`);if(!canBorrow(active.length,rating.stars))return r.status(400).json({message:'Active reservation limit reached'});const b=await call(`${urls.library}/internal/books/${bookUid}/libraries/${libraryUid}`);await call(`${urls.library}/internal/books/${bookUid}/libraries/${libraryUid}/checkout`,{method:'POST'});let reservation;try{reservation=await call(`${urls.reservation}/internal/reservations`,{method:'POST',body:JSON.stringify({username,bookUid,libraryUid,tillDate,condition:b.condition})})}catch(e){await call(`${urls.library}/internal/books/${bookUid}/libraries/${libraryUid}/return`,{method:'POST'}).catch(()=>{});throw e}r.json({reservationUid:reservation.reservationUid,status:reservation.status,startDate:reservation.startDate,tillDate:reservation.tillDate,book:{bookUid:b.bookUid,name:b.name,author:b.author,genre:b.genre},library:{libraryUid:b.libraryUid,name:b.libraryName,address:b.address,city:b.city},rating})}catch(e){n(e)}});
app.post('/api/v1/reservations/:uid/return',async(q,r,n)=>{try{const username=user(q),{condition,date}=q.body||{};if(!username||!condition||!date)return r.status(400).json({message:'X-User-Name, condition and date are required'});const reservation=await call(`${urls.reservation}/internal/reservations/${q.params.uid}?username=${encodeURIComponent(username)}`);const returned=await call(`${urls.reservation}/internal/reservations/${q.params.uid}/return`,{method:'POST',body:JSON.stringify({username,date,condition})});await call(`${urls.library}/internal/books/${reservation.bookUid}/libraries/${reservation.libraryUid}/return`,{method:'POST'});const late=new Date(date)>new Date(reservation.tillDate), damaged=condition!==reservation.rentedCondition;const delta=ratingDelta(late,!damaged);await call(`${urls.rating}/internal/rating/${encodeURIComponent(username)}/change`,{method:'POST',body:JSON.stringify({delta})});r.sendStatus(204)}catch(e){n(e)}});
app.use((e,_q,r,_n)=>{console.error(e);r.status(e.status||500).json(e.payload||{message:e.message||'Internal server error'})});app.listen(8080,'127.0.0.1');
